### PR TITLE
Add kill commands and export xterm when sshing

### PR DESCRIPTION
**Pull request by xavileon**
We now export the TERM env var before calling bash in the ssh command so commands in the container like vtysh (in quagga) or the less command work as expected. Also added a kill command so turning down a container is faster than when trying to gracefully stop them.

### CODE REVIEW

**Comment by tomoe** [comment]
@xavileon LGTM. 

I would separate the patch for kill and xterm change. A patch per logical change makes it easier for review, revert, bisect, etc. But, this time, the changes are small, so don't need to revise. 

BTW, I forgot to share my work for kill because of heavy load for other tasks:
https://github.com/midonet/midonet-sandbox/compare/master...tomoe:kill

That is a bit more DRY, but this patch looks good to me as this part shouldn't change much.

**Comment by xavileon** [comment]
Actually, these are two different commits (on a single PR though).

I really prefer your patch for killing containers. Mine was just a quick hack with zero-thought about it. We can check back next week.

**Comment by tomoe** [comment]
ah, you're right. I was just looking at the PR summary. 

> I really prefer your patch for killing containers. Mine was just a quick hack with zero-thought about it. We can check back next week.

Ok, I'll send a pull req :-) Thanks for looking into it.

**Comment by xavileon** [comment]
Code reviews are done through gerrithub.

**Pull request closed without merging**
